version: '3.1'
services:
  flask-server:
    container_name: docker-container-list-api
    build :
      dockerfile: Dockerfile.api
      context: ./
    ports:
      - 4000:5000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
  web-server:
    container_name: docker-container-list-web
    build: 
      dockerfile : Dockerfile.web
      context: ./
    ports:
      - 8083:80
    restart: unless-stopped
      
  